apiVersion: argocd-image-updater.argoproj.io/v1alpha1
kind: ImageUpdater
metadata:
  name: chess
  namespace: argocd
spec:
  writeBackConfig:
    method: "git:secret:argocd/git-creds"
    gitConfig:
      branch: main
      writeBackTarget: kustomization
  applicationRefs:
    - namePattern: chess
      images:
        - alias: chess
          imageName: "ghcr.io/dannylongeuay/cyberdan-chess-ui:1.x"
          commonUpdateSettings:
            updateStrategy: semver
