apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
  - https://raw.githubusercontent.com/argoproj-labs/argocd-image-updater/stable/config/install.yaml
  - blog-image-updater.yaml
  - c4-image-updater.yaml
  - c4-solver-image-updater.yaml
  - shift-image-updater.yaml
  - wedding-image-updater.yaml

patches:
  - path: argocd-image-updater-cm-patch.yaml
