apiVersion: argocd-image-updater.argoproj.io/v1alpha1
kind: ImageUpdater
metadata:
  name: tabs
  namespace: argocd
spec:
  writeBackConfig:
    method: "git:secret:argocd/git-creds"
    gitConfig:
      branch: main
      writeBackTarget: kustomization
  applicationRefs:
    - namePattern: tabs
      images:
        - alias: tabs
          imageName: "ghcr.io/dannylongeuay/tabs:1.x"
          commonUpdateSettings:
            updateStrategy: semver
