apiVersion: argocd-image-updater.argoproj.io/v1alpha1
kind: ImageUpdater
metadata:
  name: vizzini
  namespace: argocd
spec:
  writeBackConfig:
    method: "git:secret:argocd/git-creds"
    gitConfig:
      branch: main
      writeBackTarget: kustomization
  applicationRefs:
    - namePattern: vizzini
      images:
        - alias: vizzini
          imageName: "ghcr.io/dannylongeuay/vizzini:1.x"
          commonUpdateSettings:
            updateStrategy: semver
