apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: main
  namespace: gateway
spec:
  gatewayClassName: cilium
  infrastructure:
    annotations:
      service.beta.kubernetes.io/do-loadbalancer-certificate-id: "75b75df8-9382-47e6-9c4a-c3c23e07fc6f"
      service.beta.kubernetes.io/do-loadbalancer-protocol: "https"
      service.beta.kubernetes.io/do-loadbalancer-redirect-http-to-https: "true"
  listeners:
    - name: https
      protocol: HTTPS
      port: 443
      tls:
        mode: Terminate
        certificateRefs:
          - name: cyberdan-cert
      allowedRoutes:
        namespaces:
          from: All
    # - name: http
    #   protocol: HTTP
    #   port: 80
    #   allowedRoutes:
    #     namespaces:
    #       from: All
