provider:
  name: digitalocean

env:
  - name: DO_TOKEN
    valueFrom:
      secretKeyRef:
        name: digitalocean-token
        key: token

domainFilters:
  - cyberdan.dev

sources:
  - gateway-httproute

policy: sync

txtOwnerId: cyberdan-cluster
