apiVersion: apps/v1
kind: Deployment
metadata:
  name: lichess-cyberdan
  namespace: chess-solver
  labels:
    app: lichess-cyberdan
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lichess-cyberdan
  template:
    metadata:
      labels:
        app: lichess-cyberdan
    spec:
      containers:
        - name: lichess-cyberdan
          image: ghcr.io/dannylongeuay/cyberdan-chess-solver
          args:
            - lichess
          envFrom:
            - secretRef:
                name: lichess-token
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              memory: 128Mi
