apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: chess-solver
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/dannylongeuay/cyberdan-platform.git
    targetRevision: main
    path: workloads/chess-solver
  destination:
    server: https://kubernetes.default.svc
    namespace: chess-solver
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
