apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wedding
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/dannylongeuay/cyberdan-platform.git
    targetRevision: main
    path: workloads/wedding
  destination:
    server: https://kubernetes.default.svc
    namespace: wedding
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
